@startuml
skinparam component {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9EFF
    BorderColor        black
    ArrowColor         #222266
}

skinparam database {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9E82
    BorderColor        black
    ArrowColor         #222266
}

skinparam actor {
    BackgroundColor    #6A44ff
    BorderColor        black
    ArrowColor         #222266
}

skinparam node {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #FFA1F8
    BorderColor        black
    ArrowColor         #222266
}

node "VPN"{
    database Elasticsearch
    database Vendor_DB
    database User_info_DB

    component Logstash_1
    component Logstash_2
    component Logstash_3
    component Logstash_4
    component Logstash_5

    component Kibana
    component Admin_panel
    component Vendor_DB_API_Service
    component CV_HTTP_service
    component Nginx
    component Auth
    component Billing
    component CRM

    interface port_8000
    interface port_5601

    actor Manager
    actor DevOps

    Admin_panel -up- Vendor_DB
    Admin_panel -down- port_8000

    Vendor_DB_API_Service -up- Vendor_DB
    Vendor_DB_API_Service -down- Nginx
    Vendor_DB_API_Service -up-> Logstash_1

    CV_HTTP_service -down- Nginx
    CV_HTTP_service -right- Auth
    CV_HTTP_service -up-> Logstash_2

    Auth -down- User_info_DB
    Auth -right- Billing
    Auth -left- CRM
    Auth -up-> Logstash_3

    Billing -down- User_info_DB
    Billing -up-> Logstash_4

    CRM -down- User_info_DB
    CRM -right- Billing
    CRM -up-> Logstash_5

    Logstash_1 -up-> Elasticsearch
    Logstash_2 -up-> Elasticsearch
    Logstash_3 -up-> Elasticsearch
    Logstash_4 -up-> Elasticsearch
    Logstash_5 -up-> Elasticsearch

    Elasticsearch -right- Kibana

    Kibana -right- port_5601

    DevOps -left- port_5601

    Manager -up- port_8000
}

interface port_80
port_80 -up-- Nginx


node "Front"{
    [Web] -up- port_80
    [Mobile] -up- port_80
}

actor Client1
actor Client2

Client1 -up- Web
Client2 -up- Mobile
@enduml
