@startuml
skinparam component {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9EFF
    BorderColor        black
    ArrowColor         #222266
}

skinparam database {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9E82
    BorderColor        black
    ArrowColor         #222266
}

skinparam actor {
    BackgroundColor    #6A44ff
    BorderColor        black
    ArrowColor         #222266
}

skinparam node {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #FFA1F8
    BorderColor        black
    ArrowColor         #222266
}

node "VPN"{
    database Elasticsearch
    database Vendor_DB
    database User_info_DB
    database Redis

    component Logstash

    component Kibana
    component Admin_panel
    component Vendor_DB_API_Service
    component CV_HTTP_service
    component Nginx
    component Auth
    component Billing
    component CRM

    interface port_8000
    interface port_8001
    interface port_8002
    interface port_5432
    interface port_5601

    actor Manager
    actor DevOps

    Admin_panel -up- port_5432
    Admin_panel -down- port_8000

    Vendor_DB_API_Service -up- port_5432
    Vendor_DB_API_Service -up-> Logstash
    Vendor_DB_API_Service -down- port_8001
    port_8001 -down- Nginx

    CV_HTTP_service -right- Auth
    CV_HTTP_service -up-> Logstash
    CV_HTTP_service -down- port_8002
    port_8002 -down- Nginx

    Auth -right- User_info_DB
    Auth -down- Redis
    Auth -right- Billing
    Auth -right- CRM
    Auth -up-> Logstash

    Billing -left- User_info_DB
    Billing -up-> Logstash

    CRM -down- User_info_DB
    CRM -up- Billing
    CRM -up-> Logstash

    Logstash -up-> Elasticsearch

    Elasticsearch -right- Kibana

    Kibana -right- port_5601

    DevOps -left- port_5601

    Manager -up- port_8000

    Vendor_DB -down- port_5432
}

interface port_80
port_80 -up-- Nginx


node "Front"{
    [Web] -up- port_80
    [Mobile] -up- port_80
}

actor Client1
actor Client2

Client1 -up- Web
Client2 -up- Mobile
@enduml
