@startuml
skinparam component {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9EFF
    BorderColor        black
    ArrowColor         #222266
}

skinparam database {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9E82
    BorderColor        black
    ArrowColor         #222266
}

skinparam actor {
    BackgroundColor    #6A44ff
    BorderColor        black
    ArrowColor         #222266
}

skinparam node {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #FFA1F8
    BorderColor        black
    ArrowColor         #222266
}

node "VPN"{
    database Elasticsearch
    database Vendor_DB
    component Logstash

    component Kibana
    component Grafana
    component Admin_panel
    component Vendor_DB_API_Service
    component CV_HTTP_service
    component Nginx
    component CRM

    interface port_8000
    interface port_8001
    interface port_8002
    interface port_5432
    interface port_5601
    interface port_9200
    interface port_3000
    interface port_udp_5044

    actor Manager
    actor DevOps1
    actor DevOps2

    Admin_panel -up- port_5432
    Admin_panel -down- port_8000

    Elasticsearch -down- port_9200
    Logstash -down- port_udp_5044
    Logstash -up- port_9200

    Vendor_DB_API_Service -up- port_5432
    Vendor_DB_API_Service -up-> port_udp_5044
    Vendor_DB_API_Service -down- port_8001
    port_8001 -down- Nginx

    CV_HTTP_service -up-> port_udp_5044
    CV_HTTP_service -down- port_8002
    port_8002 -down- Nginx

    CRM -left-> port_udp_5044

    port_9200 -right- Kibana
    port_9200 -left- Grafana

    Kibana -right- port_5601
    Grafana -left- port_3000

    DevOps1 -left- port_5601
    DevOps2 -right- port_3000

    Manager -up- port_8000

    Vendor_DB -down- port_5432
}

interface port_80
port_80 -up-- Nginx


node "Front"{
    [Web] -up- port_80
    [Mobile] -up- port_80
}

actor Client1
actor Client2

Client1 -up- Web
Client2 -up- Mobile
@enduml
