@startuml
skinparam component {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9EFF
    BorderColor        black
    ArrowColor         #222266
}

skinparam database {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9E82
    BorderColor        black
    ArrowColor         #222266
}

skinparam actor {
    BackgroundColor    #6A44ff
    BorderColor        black
    ArrowColor         #222266
}

skinparam cloud {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #FFA1F8
    BorderColor        black
    ArrowColor         #222266
}

actor Client

cloud AWS {
    rectangle "Logically isolated virtual private cloud <img:VPC.png{scale=0.1}>" {


        rectangle "Availability zone 2 (private subnet)" as AZ2 {

            component "    <img:ECS.png{scale=0.2}> \n ECS" as ECS2
            component "    <img:Docker.png{scale=0.05}> \n nginx" as nginx2
            component "    <img:Docker.png{scale=0.05}> \n admin" as admin2
            component "    <img:Docker.png{scale=0.05}> \n vendor" as vendor2
            component "    <img:Docker.png{scale=0.05}> \n db" as db2
            component "    <img:Docker.png{scale=0.05}> \n cv" as cv2
            ECS2 -up- nginx2
            nginx2 -up- admin2
            nginx2 -up- vendor2
            nginx2 -up- cv2
            vendor2 -up- db2
            admin2 -up- db2
        }

        rectangle "Availability zone 1 (private subnet)" as AZ1 {
            component "    <img:ECS.png{scale=0.2}> \n ECS" as ECS1
            component "    <img:Docker.png{scale=0.05}> \n nginx" as nginx1
            component "    <img:Docker.png{scale=0.05}> \n admin" as admin1
            component "    <img:Docker.png{scale=0.05}> \n vendor" as vendor1
            component "    <img:Docker.png{scale=0.05}> \n db" as db1
            component "    <img:Docker.png{scale=0.05}> \n cv" as cv1
            ECS1 -up- nginx1
            nginx1 -up- admin1
            nginx1 -up- vendor1
            nginx1 -up- cv1
            vendor1 -up- db1
            admin1 -up- db1
        }

        rectangle "Availability zone 1,2 (public subnet)" as AZ12 {
            component "        <img:ELB.png{scale=0.2}> \n\n Load balancer " as LB
            LB -up-> ECS1
            LB -up-> ECS2
        }

    }
}

Client -up-> LB

