@startuml
skinparam component {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9EFF
    BorderColor        black
    ArrowColor         #222266
}

skinparam database {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #6A9E82
    BorderColor        black
    ArrowColor         #222266
}

skinparam actor {
    BackgroundColor    #6A44ff
    BorderColor        black
    ArrowColor         #222266
}

skinparam node {
    FontColor          black
    AttributeFontColor black
    FontSize           17
    AttributeFontSize  15
    AttributeFontname  Droid Sans Mono
    BackgroundColor    #FFA1F8
    BorderColor        black
    ArrowColor         #222266
}

node "Server"{
    component CV
    database DB
    component Admin_panel
    node HTTP_Server {
        [CV_HTTP_service] -up-[CV]
        [DB_API_Service] -up- DB
        [Nginx] -up- CV_HTTP_service : запросы фронта на обработку изображений
        [Nginx] -up- DB_API_Service : запросы фронта к базе данных
    }
    interface port_8000
    port_8000 -left- Admin_panel
    [Admin_panel] -up- DB
}

interface port_80
port_80 -up-[Nginx]


node "Front"{
    [Web] -up- port_80
    [Mobile] -up- port_80
}

actor Client1
actor Client2

Client1 -up- Web
Client2 -up- Mobile

actor Admin

Admin -left- port_8000 : управляет содержимым базы данных
@enduml
